apiVersion: v1
kind: Service
metadata:
  name: zabbixserver
  namespace: zbx
spec:
  type: NodePort
  ports:
  - port:  10051
    targetPort: 10051
    protocol: TCP
    nodePort: 30051
  selector:
    app: zabbix-server
