apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zbx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:ubuntu-5.4-latest
          imagePullPolicy: Always
          ports:
          - name: zbx-server
            containerPort: 10051
            protocol: TCP
          env:
          - name: DB_SERVER_HOST
            value: "mysql-db"
          - name: DB_SERVER_PORT
            value: "3306"
          - name: MYSQL_USER
            value: "zabbix"
          - name: MYSQL_PASSWORD
            value: "zabbix"
          - name: MYSQL_DATABASE
            value: "zabbix"
#          - name: DEBUG_MODE
#            value: "true"
#          - name: ZBX_DB_ENCRYPTION
#            value: "true"
          - name: ZBX_STATSALLOWEDIP
            value: "0.0.0.0/0"
        - name: zabbix-agent
          image: zabbix/zabbix-agent:ubuntu-5.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10050
            name: zabbix-agent
          env:
          - name: ZBX_HOSTNAME
            value: "Zabbix server"
          - name: ZBX_SERVER_HOST
            value: "127.0.0.1"
          - name: ZBX_SERVER_PORT
            value: "10051"
          - name: DEBUG_MODE
            value: "true"
