apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: zbx
spec:
  type: NodePort
  ports:
  - name: zabbix-server
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
#  - name: grafana
#    port: 80
#    protocol: TCP
#    targetPort: 80
  selector:
    app: zabbix-web
