apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zbx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - image: zabbix/zabbix-web-nginx-mysql:ubuntu-5.4-latest
        imagePullPolicy: Always
        name: zabbix-web
        ports:
        - name: zabbix-server
          containerPort: 80
        - name: grafana
          containerPort: 3000
        env:
        - name: DB_SERVER_HOST
          value: "mysql-db"
        - name:  ZBX_SERVER_HOST
          value: "zabbixserver"
        - name: ZBX_SERVER_PORT
          value: "10051"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          value: "zabbix"
        - name: ZBX_SERVER_NAME
          value: "zabbix"
        - name: TZ
          value: "Asia/Seoul"
        - name: DEBUG_MODE
          value: "true"
