kind: Deployment
apiVersion: apps/v1
metadata:
  name: react
  namespace: zbx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: anfrhrl5555/react:0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
#          volumeMounts:
#            - name: react-pv
#              mountPath: /app/build
#            - name: nginx-default-conf-pv
#              mountPath: /etc/nginx/conf.d
#      volumes:
#        - name: react-pv
#          persistentVolumeClaim:
#            claimName: react-pvc-claim
#        - name: nginx-default-conf-pv
#          persistentVolumeClaim:
#            claimName: nginx-default-conf-pvc-claim

