apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: zbx
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30006
  selector:
    app: zabbix-mysql-server
  type: NodePort
