apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-ini
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.16.142
    path: /nfs/grafana-ini
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-claim-ini
  namespace: zbx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

