apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-default-conf-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.16.142
    path: /nfs/default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-default-conf-pvc-claim
  namespace: zbx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

